### ISSUE TITLE
Script throws errors when run with no options/flags

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#536]
@yooper, when running the `whats_my_name.py` script with no params, I believe it is supposed to check all the sites against their `[me]_string` and `[me]_code` to see if they are working. When I do this, I get the below on 2 different systems.

```python
$ python3 whats_my_name.py
Traceback (most recent call last):
  File "/mnt/c/users/micah/Documents/GitHub/WhatsMyName/whats_my_name.py", line 6, in <module>
    check_for_presence()
  File "/mnt/c/users/micah/Documents/GitHub/WhatsMyName/whatsmyname/main.py", line 47, in check_for_presence
    asyncio.run(start_check_for_presence())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/mnt/c/users/micah/Documents/GitHub/WhatsMyName/whatsmyname/main.py", line 17, in start_check_for_presence
    cli_options: CliOptionsSchema = arg_parser(argparse.parse_args())
  File "/mnt/c/users/micah/Documents/GitHub/WhatsMyName/whatsmyname/app/cli/args.py", line 56, in arg_parser
    schema: CliOptionsSchema = CliOptionsSchema(**parsed)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CliOptionsSchema
usernames
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by yooper** [comment]
@WebBreacher , would the script use the known names for a site to test against?

**Comment by WebBreacher** [comment]
Yes. Exactly. One of the main requirements was for us to be able to check the strings and code to make sure they are still valid by using the known accounts to test.
